import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Banner from './Banner';
import NavBar from './NavBar';
import Footer from './Footer';

import WhatsAppPopup from './components/WhatsAppPopup';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 w-full z-50">
          <Banner />
          <NavBar />
        </div>
        {children}
        <Footer />
        <WhatsAppPopup />
      </body>
      
    </html>
  );
}
